// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Anchovy.API.Client.Models;
using Newtonsoft.Json.Linq;

namespace Anchovy.API.Client.Models
{
    public static partial class CookCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Cook> DeserializeJson(JToken inputObject)
        {
            IList<Cook> deserializedObject = new List<Cook>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Cook cook = new Cook();
                cook.DeserializeJson(iListValue);
                deserializedObject.Add(cook);
            }
            return deserializedObject;
        }
    }
}
