// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Anchovy.API.Client.Models;
using Newtonsoft.Json.Linq;

namespace Anchovy.API.Client.Models
{
    public static partial class CrustCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Crust> DeserializeJson(JToken inputObject)
        {
            IList<Crust> deserializedObject = new List<Crust>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Crust crust = new Crust();
                crust.DeserializeJson(iListValue);
                deserializedObject.Add(crust);
            }
            return deserializedObject;
        }
    }
}
