// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Anchovy.API.Client.Models;
using Newtonsoft.Json.Linq;

namespace Anchovy.API.Client.Models
{
    public static partial class LineCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Line> DeserializeJson(JToken inputObject)
        {
            IList<Line> deserializedObject = new List<Line>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Line line = new Line();
                line.DeserializeJson(iListValue);
                deserializedObject.Add(line);
            }
            return deserializedObject;
        }
    }
}
