// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Anchovy.API.Client.Models;
using Newtonsoft.Json.Linq;

namespace Anchovy.API.Client.Models
{
    public partial class Line
    {
        private int? _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private MenuListing _menuListing;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public MenuListing MenuListing
        {
            get { return this._menuListing; }
            set { this._menuListing = value; }
        }
        
        private int? _menuListingId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? MenuListingId
        {
            get { return this._menuListingId; }
            set { this._menuListingId = value; }
        }
        
        private Pizza _pizza;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public Pizza Pizza
        {
            get { return this._pizza; }
            set { this._pizza = value; }
        }
        
        private int? _pizzaId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? PizzaId
        {
            get { return this._pizzaId; }
            set { this._pizzaId = value; }
        }
        
        private int? _quantity;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Quantity
        {
            get { return this._quantity; }
            set { this._quantity = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Line class.
        /// </summary>
        public Line()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((int)idValue);
                }
                JToken menuListingValue = inputObject["MenuListing"];
                if (menuListingValue != null && menuListingValue.Type != JTokenType.Null)
                {
                    MenuListing menuListing = new MenuListing();
                    menuListing.DeserializeJson(menuListingValue);
                    this.MenuListing = menuListing;
                }
                JToken menuListingIdValue = inputObject["MenuListingId"];
                if (menuListingIdValue != null && menuListingIdValue.Type != JTokenType.Null)
                {
                    this.MenuListingId = ((int)menuListingIdValue);
                }
                JToken pizzaValue = inputObject["Pizza"];
                if (pizzaValue != null && pizzaValue.Type != JTokenType.Null)
                {
                    Pizza pizza = new Pizza();
                    pizza.DeserializeJson(pizzaValue);
                    this.Pizza = pizza;
                }
                JToken pizzaIdValue = inputObject["PizzaId"];
                if (pizzaIdValue != null && pizzaIdValue.Type != JTokenType.Null)
                {
                    this.PizzaId = ((int)pizzaIdValue);
                }
                JToken quantityValue = inputObject["Quantity"];
                if (quantityValue != null && quantityValue.Type != JTokenType.Null)
                {
                    this.Quantity = ((int)quantityValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type Line
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.Id != null)
            {
                outputObject["Id"] = this.Id.Value;
            }
            if (this.MenuListing != null)
            {
                outputObject["MenuListing"] = this.MenuListing.SerializeJson(null);
            }
            if (this.MenuListingId != null)
            {
                outputObject["MenuListingId"] = this.MenuListingId.Value;
            }
            if (this.Pizza != null)
            {
                outputObject["Pizza"] = this.Pizza.SerializeJson(null);
            }
            if (this.PizzaId != null)
            {
                outputObject["PizzaId"] = this.PizzaId.Value;
            }
            if (this.Quantity != null)
            {
                outputObject["Quantity"] = this.Quantity.Value;
            }
            return outputObject;
        }
    }
}
