// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Anchovy.API.Client.Models;
using Newtonsoft.Json.Linq;

namespace Anchovy.API.Client.Models
{
    public static partial class MenuListingCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<MenuListing> DeserializeJson(JToken inputObject)
        {
            IList<MenuListing> deserializedObject = new List<MenuListing>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                MenuListing menuListing = new MenuListing();
                menuListing.DeserializeJson(iListValue);
                deserializedObject.Add(menuListing);
            }
            return deserializedObject;
        }
    }
}
