// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Anchovy.API.Client.Models;
using Newtonsoft.Json.Linq;

namespace Anchovy.API.Client.Models
{
    public partial class MenuListing
    {
        private double? _cost;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? Cost
        {
            get { return this._cost; }
            set { this._cost = value; }
        }
        
        private int? _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        private Size _size;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public Size Size
        {
            get { return this._size; }
            set { this._size = value; }
        }
        
        private int? _sizeId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? SizeId
        {
            get { return this._sizeId; }
            set { this._sizeId = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the MenuListing class.
        /// </summary>
        public MenuListing()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken costValue = inputObject["Cost"];
                if (costValue != null && costValue.Type != JTokenType.Null)
                {
                    this.Cost = ((double)costValue);
                }
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((int)idValue);
                }
                JToken nameValue = inputObject["Name"];
                if (nameValue != null && nameValue.Type != JTokenType.Null)
                {
                    this.Name = ((string)nameValue);
                }
                JToken sizeValue = inputObject["Size"];
                if (sizeValue != null && sizeValue.Type != JTokenType.Null)
                {
                    Size size = new Size();
                    size.DeserializeJson(sizeValue);
                    this.Size = size;
                }
                JToken sizeIdValue = inputObject["SizeId"];
                if (sizeIdValue != null && sizeIdValue.Type != JTokenType.Null)
                {
                    this.SizeId = ((int)sizeIdValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type MenuListing
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.Cost != null)
            {
                outputObject["Cost"] = this.Cost.Value;
            }
            if (this.Id != null)
            {
                outputObject["Id"] = this.Id.Value;
            }
            if (this.Name != null)
            {
                outputObject["Name"] = this.Name;
            }
            if (this.Size != null)
            {
                outputObject["Size"] = this.Size.SerializeJson(null);
            }
            if (this.SizeId != null)
            {
                outputObject["SizeId"] = this.SizeId.Value;
            }
            return outputObject;
        }
    }
}
