// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Anchovy.API.Client.Models;
using Newtonsoft.Json.Linq;

namespace Anchovy.API.Client.Models
{
    public static partial class PizzaCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Pizza> DeserializeJson(JToken inputObject)
        {
            IList<Pizza> deserializedObject = new List<Pizza>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Pizza pizza = new Pizza();
                pizza.DeserializeJson(iListValue);
                deserializedObject.Add(pizza);
            }
            return deserializedObject;
        }
    }
}
