// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Anchovy.API.Client.Models;
using Newtonsoft.Json.Linq;

namespace Anchovy.API.Client.Models
{
    public static partial class SauceCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Sauce> DeserializeJson(JToken inputObject)
        {
            IList<Sauce> deserializedObject = new List<Sauce>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Sauce sauce = new Sauce();
                sauce.DeserializeJson(iListValue);
                deserializedObject.Add(sauce);
            }
            return deserializedObject;
        }
    }
}
