// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Anchovy.API.Client.Models;
using Newtonsoft.Json.Linq;

namespace Anchovy.API.Client.Models
{
    public static partial class ShiftCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Shift> DeserializeJson(JToken inputObject)
        {
            IList<Shift> deserializedObject = new List<Shift>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Shift shift = new Shift();
                shift.DeserializeJson(iListValue);
                deserializedObject.Add(shift);
            }
            return deserializedObject;
        }
    }
}
