// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Anchovy.API.Client.Models
{
    public partial class Topping
    {
        private double? _cost;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? Cost
        {
            get { return this._cost; }
            set { this._cost = value; }
        }
        
        private int? _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private int? _lowLevel;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? LowLevel
        {
            get { return this._lowLevel; }
            set { this._lowLevel = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        private int? _quantity;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Quantity
        {
            get { return this._quantity; }
            set { this._quantity = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Topping class.
        /// </summary>
        public Topping()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken costValue = inputObject["Cost"];
                if (costValue != null && costValue.Type != JTokenType.Null)
                {
                    this.Cost = ((double)costValue);
                }
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((int)idValue);
                }
                JToken lowLevelValue = inputObject["LowLevel"];
                if (lowLevelValue != null && lowLevelValue.Type != JTokenType.Null)
                {
                    this.LowLevel = ((int)lowLevelValue);
                }
                JToken nameValue = inputObject["Name"];
                if (nameValue != null && nameValue.Type != JTokenType.Null)
                {
                    this.Name = ((string)nameValue);
                }
                JToken quantityValue = inputObject["Quantity"];
                if (quantityValue != null && quantityValue.Type != JTokenType.Null)
                {
                    this.Quantity = ((int)quantityValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type Topping
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.Cost != null)
            {
                outputObject["Cost"] = this.Cost.Value;
            }
            if (this.Id != null)
            {
                outputObject["Id"] = this.Id.Value;
            }
            if (this.LowLevel != null)
            {
                outputObject["LowLevel"] = this.LowLevel.Value;
            }
            if (this.Name != null)
            {
                outputObject["Name"] = this.Name;
            }
            if (this.Quantity != null)
            {
                outputObject["Quantity"] = this.Quantity.Value;
            }
            return outputObject;
        }
    }
}
