// <auto-generated />
namespace Anchovy.API.Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class manytomany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(manytomany));
        
        string IMigrationMetadata.Id
        {
            get { return "201611150637508_many to many"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
