// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Anchovy.API.Client.Models;
using Newtonsoft.Json.Linq;

namespace Anchovy.API.Client.Models
{
    public static partial class ManagerCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Manager> DeserializeJson(JToken inputObject)
        {
            IList<Manager> deserializedObject = new List<Manager>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Manager manager = new Manager();
                manager.DeserializeJson(iListValue);
                deserializedObject.Add(manager);
            }
            return deserializedObject;
        }
    }
}
