// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Anchovy.API.Client.Models;
using Newtonsoft.Json.Linq;

namespace Anchovy.API.Client.Models
{
    public partial class OrderLine
    {
        private int? _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private Line _line;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public Line Line
        {
            get { return this._line; }
            set { this._line = value; }
        }
        
        private int? _lineId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? LineId
        {
            get { return this._lineId; }
            set { this._lineId = value; }
        }
        
        private Order _order;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public Order Order
        {
            get { return this._order; }
            set { this._order = value; }
        }
        
        private int? _orderId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? OrderId
        {
            get { return this._orderId; }
            set { this._orderId = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the OrderLine class.
        /// </summary>
        public OrderLine()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((int)idValue);
                }
                JToken lineValue = inputObject["Line"];
                if (lineValue != null && lineValue.Type != JTokenType.Null)
                {
                    Line line = new Line();
                    line.DeserializeJson(lineValue);
                    this.Line = line;
                }
                JToken lineIdValue = inputObject["LineId"];
                if (lineIdValue != null && lineIdValue.Type != JTokenType.Null)
                {
                    this.LineId = ((int)lineIdValue);
                }
                JToken orderValue = inputObject["Order"];
                if (orderValue != null && orderValue.Type != JTokenType.Null)
                {
                    Order order = new Order();
                    order.DeserializeJson(orderValue);
                    this.Order = order;
                }
                JToken orderIdValue = inputObject["OrderId"];
                if (orderIdValue != null && orderIdValue.Type != JTokenType.Null)
                {
                    this.OrderId = ((int)orderIdValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type OrderLine
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.Id != null)
            {
                outputObject["Id"] = this.Id.Value;
            }
            if (this.Line != null)
            {
                outputObject["Line"] = this.Line.SerializeJson(null);
            }
            if (this.LineId != null)
            {
                outputObject["LineId"] = this.LineId.Value;
            }
            if (this.Order != null)
            {
                outputObject["Order"] = this.Order.SerializeJson(null);
            }
            if (this.OrderId != null)
            {
                outputObject["OrderId"] = this.OrderId.Value;
            }
            return outputObject;
        }
    }
}
