// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Anchovy.API.Client.Models;
using Newtonsoft.Json.Linq;

namespace Anchovy.API.Client.Models
{
    public partial class Order
    {
        private DateTimeOffset? _cancelledTimeStamp;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? CancelledTimeStamp
        {
            get { return this._cancelledTimeStamp; }
            set { this._cancelledTimeStamp = value; }
        }
        
        private DateTimeOffset? _claimedTimeStamp;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? ClaimedTimeStamp
        {
            get { return this._claimedTimeStamp; }
            set { this._claimedTimeStamp = value; }
        }
        
        private DateTimeOffset? _completedTimeStamp;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? CompletedTimeStamp
        {
            get { return this._completedTimeStamp; }
            set { this._completedTimeStamp = value; }
        }
        
        private Cook _cook;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public Cook Cook
        {
            get { return this._cook; }
            set { this._cook = value; }
        }
        
        private int? _cookId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? CookId
        {
            get { return this._cookId; }
            set { this._cookId = value; }
        }
        
        private Customer _customer;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public Customer Customer
        {
            get { return this._customer; }
            set { this._customer = value; }
        }
        
        private int? _customerId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? CustomerId
        {
            get { return this._customerId; }
            set { this._customerId = value; }
        }
        
        private int? _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private DateTimeOffset? _orderedTimeStamp;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? OrderedTimeStamp
        {
            get { return this._orderedTimeStamp; }
            set { this._orderedTimeStamp = value; }
        }
        
        private int? _orderStatus;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? OrderStatus
        {
            get { return this._orderStatus; }
            set { this._orderStatus = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Order class.
        /// </summary>
        public Order()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken cancelledTimeStampValue = inputObject["CancelledTimeStamp"];
                if (cancelledTimeStampValue != null && cancelledTimeStampValue.Type != JTokenType.Null)
                {
                    this.CancelledTimeStamp = ((DateTimeOffset)cancelledTimeStampValue);
                }
                JToken claimedTimeStampValue = inputObject["ClaimedTimeStamp"];
                if (claimedTimeStampValue != null && claimedTimeStampValue.Type != JTokenType.Null)
                {
                    this.ClaimedTimeStamp = ((DateTimeOffset)claimedTimeStampValue);
                }
                JToken completedTimeStampValue = inputObject["CompletedTimeStamp"];
                if (completedTimeStampValue != null && completedTimeStampValue.Type != JTokenType.Null)
                {
                    this.CompletedTimeStamp = ((DateTimeOffset)completedTimeStampValue);
                }
                JToken cookValue = inputObject["Cook"];
                if (cookValue != null && cookValue.Type != JTokenType.Null)
                {
                    Cook cook = new Cook();
                    cook.DeserializeJson(cookValue);
                    this.Cook = cook;
                }
                JToken cookIdValue = inputObject["CookId"];
                if (cookIdValue != null && cookIdValue.Type != JTokenType.Null)
                {
                    this.CookId = ((int)cookIdValue);
                }
                JToken customerValue = inputObject["Customer"];
                if (customerValue != null && customerValue.Type != JTokenType.Null)
                {
                    Customer customer = new Customer();
                    customer.DeserializeJson(customerValue);
                    this.Customer = customer;
                }
                JToken customerIdValue = inputObject["CustomerId"];
                if (customerIdValue != null && customerIdValue.Type != JTokenType.Null)
                {
                    this.CustomerId = ((int)customerIdValue);
                }
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((int)idValue);
                }
                JToken orderedTimeStampValue = inputObject["OrderedTimeStamp"];
                if (orderedTimeStampValue != null && orderedTimeStampValue.Type != JTokenType.Null)
                {
                    this.OrderedTimeStamp = ((DateTimeOffset)orderedTimeStampValue);
                }
                JToken orderStatusValue = inputObject["OrderStatus"];
                if (orderStatusValue != null && orderStatusValue.Type != JTokenType.Null)
                {
                    this.OrderStatus = ((int)orderStatusValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type Order
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.CancelledTimeStamp != null)
            {
                outputObject["CancelledTimeStamp"] = this.CancelledTimeStamp.Value;
            }
            if (this.ClaimedTimeStamp != null)
            {
                outputObject["ClaimedTimeStamp"] = this.ClaimedTimeStamp.Value;
            }
            if (this.CompletedTimeStamp != null)
            {
                outputObject["CompletedTimeStamp"] = this.CompletedTimeStamp.Value;
            }
            if (this.Cook != null)
            {
                outputObject["Cook"] = this.Cook.SerializeJson(null);
            }
            if (this.CookId != null)
            {
                outputObject["CookId"] = this.CookId.Value;
            }
            if (this.Customer != null)
            {
                outputObject["Customer"] = this.Customer.SerializeJson(null);
            }
            if (this.CustomerId != null)
            {
                outputObject["CustomerId"] = this.CustomerId.Value;
            }
            if (this.Id != null)
            {
                outputObject["Id"] = this.Id.Value;
            }
            if (this.OrderedTimeStamp != null)
            {
                outputObject["OrderedTimeStamp"] = this.OrderedTimeStamp.Value;
            }
            if (this.OrderStatus != null)
            {
                outputObject["OrderStatus"] = this.OrderStatus.Value;
            }
            return outputObject;
        }
    }
}
