// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Anchovy.API.Client.Models;
using Newtonsoft.Json.Linq;

namespace Anchovy.API.Client.Models
{
    public static partial class PizzaToppingCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<PizzaTopping> DeserializeJson(JToken inputObject)
        {
            IList<PizzaTopping> deserializedObject = new List<PizzaTopping>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                PizzaTopping pizzaTopping = new PizzaTopping();
                pizzaTopping.DeserializeJson(iListValue);
                deserializedObject.Add(pizzaTopping);
            }
            return deserializedObject;
        }
    }
}
