// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Anchovy.API.Client.Models;
using Newtonsoft.Json.Linq;

namespace Anchovy.API.Client.Models
{
    public static partial class ToppingCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Topping> DeserializeJson(JToken inputObject)
        {
            IList<Topping> deserializedObject = new List<Topping>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Topping topping = new Topping();
                topping.DeserializeJson(iListValue);
                deserializedObject.Add(topping);
            }
            return deserializedObject;
        }
    }
}
